# Generated by Django 2.0 on 2018-04-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repeate_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Repeate_type', models.TextField( )),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('complete', models.BooleanField()),
                ('repeate_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Repeate_type')),
            ],
        ),
        migrations.CreateModel(
            name='Task_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
                ('in_order', models.BooleanField()),
                ('complete', models.BooleanField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.EmailField(max_length=254)),
                ('user_password', models.TextField()),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Task')),
            ],
        ),
    ]
