# Generated by Django 2.0 on 2018-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='repeate_type_id',
            new_name='repeate_type',
        ),
        migrations.AddField(
            model_name='task_item',
            name='step_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
