# Generated by Django 2.0 on 2018-04-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20180408_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='repeate_type',
            new_name='repeate_type_id',
        ),
        migrations.RemoveField(
            model_name='task_item',
            name='step_num',
        ),
    ]
