# Generated by Django 2.0 on 2018-04-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20180408_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_title',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
